// SkySaver — airport list for the plan wizard combobox.
// Mirrors backend airports.py so search hits everywhere.
window.SKY_AIRPORTS = [
  { code: 'LHR', city: 'London Heathrow', country: 'United Kingdom' },
  { code: 'LGW', city: 'London Gatwick', country: 'United Kingdom' },
  { code: 'STN', city: 'London Stansted', country: 'United Kingdom' },
  { code: 'LCY', city: 'London City', country: 'United Kingdom' },
  { code: 'MAN', city: 'Manchester', country: 'United Kingdom' },
  { code: 'EDI', city: 'Edinburgh', country: 'United Kingdom' },
  { code: 'DUB', city: 'Dublin', country: 'Ireland' },
  { code: 'CDG', city: 'Paris Charles de Gaulle', country: 'France' },
  { code: 'ORY', city: 'Paris Orly', country: 'France' },
  { code: 'AMS', city: 'Amsterdam Schiphol', country: 'Netherlands' },
  { code: 'FRA', city: 'Frankfurt', country: 'Germany' },
  { code: 'MUC', city: 'Munich', country: 'Germany' },
  { code: 'BER', city: 'Berlin', country: 'Germany' },
  { code: 'MAD', city: 'Madrid Barajas', country: 'Spain' },
  { code: 'BCN', city: 'Barcelona', country: 'Spain' },
  { code: 'FCO', city: 'Rome Fiumicino', country: 'Italy' },
  { code: 'MXP', city: 'Milan Malpensa', country: 'Italy' },
  { code: 'ZRH', city: 'Zurich', country: 'Switzerland' },
  { code: 'VIE', city: 'Vienna', country: 'Austria' },
  { code: 'CPH', city: 'Copenhagen', country: 'Denmark' },
  { code: 'ARN', city: 'Stockholm Arlanda', country: 'Sweden' },
  { code: 'OSL', city: 'Oslo', country: 'Norway' },
  { code: 'HEL', city: 'Helsinki', country: 'Finland' },
  { code: 'LIS', city: 'Lisbon', country: 'Portugal' },
  { code: 'ATH', city: 'Athens', country: 'Greece' },
  { code: 'IST', city: 'Istanbul', country: 'Turkey' },
  { code: 'SAW', city: 'Istanbul Sabiha Gokcen', country: 'Turkey' },
  { code: 'WAW', city: 'Warsaw', country: 'Poland' },
  { code: 'PRG', city: 'Prague', country: 'Czech Republic' },
  { code: 'BRU', city: 'Brussels', country: 'Belgium' },
  { code: 'JFK', city: 'New York JFK', country: 'United States' },
  { code: 'LGA', city: 'New York LaGuardia', country: 'United States' },
  { code: 'EWR', city: 'New York Newark', country: 'United States' },
  { code: 'BOS', city: 'Boston Logan', country: 'United States' },
  { code: 'PHL', city: 'Philadelphia', country: 'United States' },
  { code: 'IAD', city: 'Washington Dulles', country: 'United States' },
  { code: 'DCA', city: 'Washington Reagan', country: 'United States' },
  { code: 'MIA', city: 'Miami', country: 'United States' },
  { code: 'MCO', city: 'Orlando', country: 'United States' },
  { code: 'ATL', city: 'Atlanta', country: 'United States' },
  { code: 'DFW', city: 'Dallas Fort Worth', country: 'United States' },
  { code: 'IAH', city: 'Houston Intercontinental', country: 'United States' },
  { code: 'ORD', city: 'Chicago O\'Hare', country: 'United States' },
  { code: 'MDW', city: 'Chicago Midway', country: 'United States' },
  { code: 'DTW', city: 'Detroit', country: 'United States' },
  { code: 'MSP', city: 'Minneapolis St Paul', country: 'United States' },
  { code: 'DEN', city: 'Denver', country: 'United States' },
  { code: 'SLC', city: 'Salt Lake City', country: 'United States' },
  { code: 'PHX', city: 'Phoenix', country: 'United States' },
  { code: 'LAS', city: 'Las Vegas', country: 'United States' },
  { code: 'LAX', city: 'Los Angeles', country: 'United States' },
  { code: 'SFO', city: 'San Francisco', country: 'United States' },
  { code: 'SAN', city: 'San Diego', country: 'United States' },
  { code: 'SEA', city: 'Seattle Tacoma', country: 'United States' },
  { code: 'PDX', city: 'Portland', country: 'United States' },
  { code: 'YYZ', city: 'Toronto Pearson', country: 'Canada' },
  { code: 'YVR', city: 'Vancouver', country: 'Canada' },
  { code: 'YUL', city: 'Montreal', country: 'Canada' },
  { code: 'MEX', city: 'Mexico City', country: 'Mexico' },
  { code: 'CUN', city: 'Cancun', country: 'Mexico' },
  { code: 'GRU', city: 'Sao Paulo Guarulhos', country: 'Brazil' },
  { code: 'EZE', city: 'Buenos Aires Ezeiza', country: 'Argentina' },
  { code: 'BOG', city: 'Bogota', country: 'Colombia' },
  { code: 'LIM', city: 'Lima', country: 'Peru' },
  { code: 'DXB', city: 'Dubai', country: 'United Arab Emirates' },
  { code: 'AUH', city: 'Abu Dhabi', country: 'United Arab Emirates' },
  { code: 'DOH', city: 'Doha Hamad', country: 'Qatar' },
  { code: 'BAH', city: 'Bahrain', country: 'Bahrain' },
  { code: 'RUH', city: 'Riyadh', country: 'Saudi Arabia' },
  { code: 'JED', city: 'Jeddah', country: 'Saudi Arabia' },
  { code: 'KWI', city: 'Kuwait', country: 'Kuwait' },
  { code: 'TLV', city: 'Tel Aviv', country: 'Israel' },
  { code: 'CAI', city: 'Cairo', country: 'Egypt' },
  { code: 'JNB', city: 'Johannesburg', country: 'South Africa' },
  { code: 'CPT', city: 'Cape Town', country: 'South Africa' },
  { code: 'LOS', city: 'Lagos', country: 'Nigeria' },
  { code: 'NBO', city: 'Nairobi', country: 'Kenya' },
  { code: 'ADD', city: 'Addis Ababa', country: 'Ethiopia' },
  { code: 'BOM', city: 'Mumbai', country: 'India' },
  { code: 'DEL', city: 'Delhi', country: 'India' },
  { code: 'BLR', city: 'Bangalore', country: 'India' },
  { code: 'MAA', city: 'Chennai', country: 'India' },
  { code: 'HYD', city: 'Hyderabad', country: 'India' },
  { code: 'CCU', city: 'Kolkata', country: 'India' },
  { code: 'GOI', city: 'Goa', country: 'India' },
  { code: 'COK', city: 'Kochi', country: 'India' },
  { code: 'CMB', city: 'Colombo', country: 'Sri Lanka' },
  { code: 'KTM', city: 'Kathmandu', country: 'Nepal' },
  { code: 'DAC', city: 'Dhaka', country: 'Bangladesh' },
  { code: 'BKK', city: 'Bangkok Suvarnabhumi', country: 'Thailand' },
  { code: 'DMK', city: 'Bangkok Don Mueang', country: 'Thailand' },
  { code: 'HKT', city: 'Phuket', country: 'Thailand' },
  { code: 'CNX', city: 'Chiang Mai', country: 'Thailand' },
  { code: 'SIN', city: 'Singapore Changi', country: 'Singapore' },
  { code: 'KUL', city: 'Kuala Lumpur', country: 'Malaysia' },
  { code: 'CGK', city: 'Jakarta', country: 'Indonesia' },
  { code: 'DPS', city: 'Bali Denpasar', country: 'Indonesia' },
  { code: 'MNL', city: 'Manila', country: 'Philippines' },
  { code: 'HAN', city: 'Hanoi', country: 'Vietnam' },
  { code: 'SGN', city: 'Ho Chi Minh City', country: 'Vietnam' },
  { code: 'PNH', city: 'Phnom Penh', country: 'Cambodia' },
  { code: 'HKG', city: 'Hong Kong', country: 'Hong Kong' },
  { code: 'TPE', city: 'Taipei Taoyuan', country: 'Taiwan' },
  { code: 'PEK', city: 'Beijing Capital', country: 'China' },
  { code: 'PKX', city: 'Beijing Daxing', country: 'China' },
  { code: 'PVG', city: 'Shanghai Pudong', country: 'China' },
  { code: 'SHA', city: 'Shanghai Hongqiao', country: 'China' },
  { code: 'CAN', city: 'Guangzhou', country: 'China' },
  { code: 'SZX', city: 'Shenzhen', country: 'China' },
  { code: 'ICN', city: 'Seoul Incheon', country: 'South Korea' },
  { code: 'GMP', city: 'Seoul Gimpo', country: 'South Korea' },
  { code: 'HND', city: 'Tokyo Haneda', country: 'Japan' },
  { code: 'NRT', city: 'Tokyo Narita', country: 'Japan' },
  { code: 'KIX', city: 'Osaka Kansai', country: 'Japan' },
  { code: 'FUK', city: 'Fukuoka', country: 'Japan' },
  { code: 'SYD', city: 'Sydney', country: 'Australia' },
  { code: 'MEL', city: 'Melbourne', country: 'Australia' },
  { code: 'BNE', city: 'Brisbane', country: 'Australia' },
  { code: 'PER', city: 'Perth', country: 'Australia' },
  { code: 'ADL', city: 'Adelaide', country: 'Australia' },
  { code: 'AKL', city: 'Auckland', country: 'New Zealand' },
  { code: 'WLG', city: 'Wellington', country: 'New Zealand' },
];
